[package]
name = "wakeup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version ="3.2.16", features=["regex"]}
hex = "0.4.3"
regex = "1.6.0"