# .github/workflows/release.yml

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  quickcheck:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo pkgid
    - run: cargo pkgid | cut -d# -f2
    - id: rustversion
      run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          #- target: x86_64-unknown-linux-gnu
          #  archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-apple-darwin
            archive: zip
          #- target: aarch64-apple-darwin
          #  archive: zip
          - target:  x86_64-pc-windows-gnu
            archive: zip            
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md LICENSE"
  deb:
    name: Generate deb
    needs: [quickcheck, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo install cargo-deb
      - uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --target x86_64-unknown-linux-gnu -o ./wakeup_${{ needs.quickcheck.outputs.version }}_amd64.deb
          
      - name: Release deb
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wakeup_${{ needs.quickcheck.outputs.version }}_amd64.deb
